spring.application.name=productService

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/nurseryProductDb
spring.datasource.username=postgres
spring.datasource.password=1210
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false